/** @type {import('next').NextConfig} */
const nextConfig = {
    images: {
        // domains: ['indiasweethouse.in'],  // Add the domain here
        remotePatterns: [
          {
            protocol: "https",
            hostname: "indiasweethouse.in",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "cdn.uengage.io",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "shwetainthekitchen.com",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "encrypted-tbn0.gstatic.com",
            port: "",
            pathname: "/**",
          },
          
          {
            protocol: "https",
            hostname: "static.toiimg.com",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "spicecravings.com",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "encrypted-tbn0.gstatic.com",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "sapanarestaurant.com",
            port: "",
            pathname: "/**",
          },
          {
            protocol: "https",
            hostname: "upload.wikimedia.org",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.indianhealthyrecipes.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.nehascookbook.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "masalaandchai.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.cubesnjuliennes.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.saffrontrail.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "kannanskitchen.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.indianhealthyrecipes.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "www.vegrecipesofindia.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "encrypted-tbn0.gstatic.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "shwetainthekitchen.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.spiceupthecurry.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "thewanderlustkitchen.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "vegecravings.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.indianveggiedelight.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "carveyourcraving.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.awesomecuisine.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.cubesnjuliennes.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "paattiskitchen.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "www.yummytummyaarthi.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "cdn1.foodviva.com",
            port: "",
            pathname: "/**",
          },
             {
            protocol: "https",
            hostname: "justhomemade.files.wordpress.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.rachelgurjar.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.tastycircle.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.flavourstreat.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "rakskitchen.net",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.cookwithkushi.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.sharmispassions.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "www.indianveggiedelight.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "s3-ap-south-1.amazonaws.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "jalaramsweetcentre.com",
            port: "",
            pathname: "/**",
          },
           {
            protocol: "https",
            hostname: "encrypted-tbn0.gstatic.com",
            port: "",
            pathname: "/**",
          },
            {
            protocol: "https",
            hostname: "dilchad.com",
            port: "",
            pathname: "/**",
          },

        ],
      },
};

export default nextConfig;
